name: Code Review

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: npm install
        run: |
          npm install
          npm install --save-dev @babel/plugin-transform-flow-strip-types

        env:
          CI: true
    
      - name: Danger JS Action
        uses: danger/danger-js@9.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}