name: Danger-Test

on:
  pull_request:
    branches:
      - master
      - develop
      - feature/*
      - release/*

jobs:
  danger:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Danger JS Action
      uses: ./scripts/run-danger/
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
