name: Danger-Test

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - release/*

jobs:
  danger:

    runs-on: ubuntu-latest
    
    steps:
    - name: Danger JS Action
      uses: ./scripts/run-danger/
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}