name: Danger-PR

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - release/*

jobs:
  danger:

    runs-on: macOS-latest
    

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Danger JS Action
      uses: danger/danger-js@9.1.8
