name: Swift

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - release/*

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild build test -destination 'name=iPhone 11' -scheme 'X3'


