name: Swift

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - release/*

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v
      with:
        python-version: '3.7'
    - name: Run python for test
      run: python ./scripts/test.py


